### ISSUE TITLE
Why does `generate` verb requires accessing underlying cluster

### ISSUE THREAD

**Issue by chaodaiG** [external-secrets/kes-to-eso#10]
Our use case is that all cluster operations are done through code, so ESO yaml generated from static KES yaml is desired. And for security concerns my `kubeconfig config current-context` is always set to nil, when running:
```
kestoeso --input ./in --output ./out
```
and got error:
```
FATA[0000] invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```

I'm reluctant to run this command with KUBECONFIG supplied unless the reason for this requirement is well documented

**Comment by moolen** [comment]
From the CLI help:

```
It reads kubernetes-external-secrets deployment declaration and uses
this information alongside with any KES externalSecrets declaration to
provide ESO SecretStores and ExternalSecrets definitions.
```

It actually looks into your cluster and tries to infer authentication properties from the KES deployment.

**Comment by chaodaiG** [comment]
> From the CLI help:
> 
> ```
> It reads kubernetes-external-secrets deployment declaration and uses
> this information alongside with any KES externalSecrets declaration to
> provide ESO SecretStores and ExternalSecrets definitions.
> ```
> 
> It actually looks into your cluster and tries to infer authentication properties from the KES deployment.

Thanks! I'm not super convinced that this is necessary for static config generation.

for example for a KES config:
```
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: service-account
  namespace: test-pods
spec:
  backendType: gcpSecretsManager
  projectId: k8s-prow-builds
  data:
  - key: default-k8s-build-cluster-service-account-key
    name: service-account.json
    version: latest
```

The expected ESO config can be derived without looking in the cluster:
```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: k8s-prow-builds
spec:
  provider:
    gcpsm:
      projectID: k8s-prow-builds
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: k8s-prow-build-service-account
  namespace: test-pods
spec:
  refreshInterval: 10s           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: SecretStore
    name: k8s-prow-builds               # name of the SecretStore (or kind specified)
  target:
    name: service-account  # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
  - secretKey: default-k8s-build-cluster-service-account-key  # name of the GCPSM secret key
    remoteRef:
      key: service-account.json
```
