### ISSUE TITLE
Error: no Auth Provider found for name "gcp"

### ISSUE THREAD

**Issue by kenske** [external-secrets/kes-to-eso#3]
I'm getting the above error trying to covert the following:

```
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: db-creds
spec:
  backendType: gcpSecretsManager
  data:
    - key: db
      property: username
      name: DB_USERNAME
    - key: db
      property: password
      name: DB_PASSWORD
```

Is GCP not supported?
